export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const LOGIN_WITH_USERNAME = 'LOGIN_WITH_USERNAME';
export const CREATE_NEW_CHANNEL = 'CREATE_NEW_CHANNEL';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const TYPING_UPDATE = 'TYPING_UPDATE';
export const ONLINE_USER ='ONLINE_USER';
export const FIND_USERS = 'FIND_USERS';